### ISSUE TITLE
Investigate adding `QT_STYLE_OVERRIDE=''` to the list of environment variables

### ISSUE THREAD

**Issue by guihkx** [flathub/io.github.nuttyartist.notes#1]
Just something to remind myself before the next release...

Users of [adwaita-qt](https://github.com/FedoraQt/adwaita-qt), which is apparently used by default in some GNOME-based distros like Fedora, might experience UI breakage for the next release.

The reason being that the following pull requests have introduced QML-based interface in the app:

- https://github.com/nuttyartist/notes/pull/574
- https://github.com/nuttyartist/notes/pull/589

And now when you launch the app using the terminal, you may see these messages:

```
$ notes
qrc:/qt/qml/EditorSettings.qml: module "Adwaita" is not installed
qrc:/qt/qml/kanbanMain.qml: module "Adwaita" is not installed
```

Which might seem harmless, but if you try to either switch to the kanban view (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>), or even open the new settings menu, nothing will happen.

This appears to be a bug in Qt:

- https://bugreports.qt.io/browse/QTBUG-99889

And the workarounds I found on the internet all consist of setting the `QT_STYLE_OVERRIDE` environment variable to a an empty value before launching the app, which we might end up doing here for the next release.

Since we don't have a lot of native-looking UI elements (where users of adwaita-qt would benefit the most, I think), I believe this workaround is acceptable - assuming it works, of course.

If you're aware of different workarounds/solutions, feel free to chime in as well.

**Comment by nuttyartist** [comment]
Oy... Good catch tho!

**Comment by guihkx** [comment]
v2.2.0 is out, but I don't think I'll add this yet, because I don't want to potentially break whatever theme they might be using.

So I guess we should wait until we get actual reports from users experiencing some sort of breakage of QML-related interfaces.

In any case, I think this can stay open.

**Comment by nuttyartist** [comment]
> So I guess we should wait until we get actual reports from users experiencing some sort of breakage of QML-related interfaces.

I agree. Does this bug only occur on Flatpak?

**Comment by guihkx** [comment]
No, on Linux at least I can easily reproduce the problem by forcing a Qt style (existent or otherwise) e.g.:

```
$ notes -style adwaita
# or
$ notes -style foo
```

**Comment by guihkx** [comment]
Revisiting this...

> No, on Linux at least I can easily reproduce the problem by forcing a Qt style (existent or otherwise) e.g.:
> 
> ```
> $ notes -style adwaita
> # or
> $ notes -style foo
> ```

This is not reproducible anymore, as of Qt 6.6.3. A workaround should not be needed.

**Comment by bjorn** [comment]
@guihkx Would that feedback be useful on the Qt bug as well, which still appears to be open? Or is that issue still valid anyway?

**Comment by guihkx** [comment]
Hmm, you're right. I'll verify which exact Qt version fixed the issue and post there.

**EDIT**: Done.
